website:
  title: "Tin Buenafe"
  description: "UQ PhD candidate | Climate-smart MSP"
  
  favicon: img/logo_compressed.png
  
  navbar:
    pinned: true
    logo: img/logo.png
    
  search: false

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222 # trying to use the same port
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: false

format:
  html:
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
